name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Chạy khi bạn push code lên nhánh main (hoặc master)

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            - name: Install and Build 🔧
              run: |
                  npm install
                  npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist # Thư mục build của Vite
                  branch: gh-pages # Nhánh GitHub Pages sẽ dùng
